### ISSUE TITLE
How to change SOURCESBUCKET parameter after installation

### ISSUE THREAD

**Issue by howieleicht** [OHDSI/OHDSIonAWS#12]
We successfully installed OHDSI on AWS and are able to work with the synthetic sources.  SOURCESBUCKET is set to the default ohdsi-sample-data.   Now we'd like to work with our real sources - we've created the appropriate sql files, and now we'd like to create the new source mappings via Atlas.  But we can't find any documentation which would inform us as to how to change the SOURCESBUCKET to our own S3 bucket, or where any deployment parameters are stored and can be edited.

**Comment by don-torok** [comment]
I suggest you re-enter your question to the Implementers Forum since this is a question rather than an issue, you are more likely to get an answer.  Look at WebAPI documentation for source and source_daimon table setup
